### ISSUE TITLE
Error building site: TOCSS: failed to transform "sass/styles.scss"

### ISSUE THREAD

**Issue by georgew509** [frjo/hugo-theme-zen#60]
I installed your latest Zen theme update:

`$ git submodule update --remote --merge`

And I am now seeing a build error:

```
george@imac1:~/Hugo/apcom
$ hugo server
Start building sites … 
hugo v0.99.1+extended darwin/amd64 BuildDate=unknown
Error: Error building site: TOCSS: failed to transform "sass/styles.scss" (text/x-scss): "/Users/george/Hugo/apcom/themes/zen/assets/sass/reset/sections/_sections.scss:80:16": Undefined variable: "$max-line-width".
Built in 532 ms
```

**Comment by frjo** [comment]
My guess is that you have overridden `_variables.scss`. Update that file from the original in the Zen theme and you will find the new `$max-line-width` variable.

Some time back I added an empty `_extra.scss` file. This file is loaded after `_variables.scss` so can be used to override variables. I recommend using this instead of overriding `_variables.scss`.
