### ISSUE TITLE
Cdn url misses a / in rss feed

### ISSUE THREAD

**Issue by metasikander** [frjo/hugo-theme-zen#71]
Site: https://antihashed.xyz
Repo: https://github.com/metasikander/antihashed

Cdn config line:
`    cdn:  "https://antihashed.us-east-1.linodeobjects.com"    `

rss.xml result line in https://antihashed.xyz/podcast/index.xml:
`<enclosure url="https:/antihashed.us-east-1.linodeobjects.com/episode_005.m4a" type="audio/mpeg"/>`
---
The url in the xml is missing a / after https:, so some podcast players can't fetch the file (while others handles it apparently).
Updated to the latest version of the template, and hugo.

**Comment by frjo** [comment]
A bug I introduced in commit https://github.com/frjo/hugo-theme-zen/commit/56d3c30a9830f728ac9a354e8b53b52a125be8f9

I have reverted it back to use "add" instead of "path.Join" now in the main branch.

If you can confirm it is working I will make a new release.

Thanks for the report and for using the Zen theme!

**Comment by metasikander** [comment]
yes. it is now correct.
thank you!
